### ISSUE TITLE
What happened to Unity ASL Generator?

### ISSUE THREAD

**Issue by TypicallyThomas** [just-ero/AutoSplitHelp#1]
Hi, a while back I made a script for a game called Not for Broadcast using your Unity ASL generator. What happened to it? You were making a new update for it, and it seemed absolutely brilliant. Could you tell me if a version is still available somewhere?

**Comment by just-ero** [comment]
Maintaining the project becomes increasingly impossible. There are too many Unity versions to cover, Unity versions on which the SceneManager doesn't work (or isn't used), and it's just confusing for everybody.

So no, there is no version available.
