### ISSUE TITLE
KeyNotFoundException on attempting to find classes in Assembly-CSharp

### ISSUE THREAD

**Issue by Tiyenti** [just-ero/AutoSplitHelp#2]
per Tiyenti/distance.asl#12. It seems that, at least in the Distance autosplitter, mono loading ends up aborting with a `KeyNotFoundException` with the following output/stack trace:

![image](https://user-images.githubusercontent.com/11019859/153773681-f7cca2f3-856a-4a90-bfad-6f0cad78081e.png)

Loading the `String` and `Dictionary` classes from `mscorlib` works successfully, but every attempt at loading a class from `Assembly-CSharp` fails with this result. I've tried re-ordering the class definitions in the autosplitter script but this has not made a difference. Attempting to hotfix this by wrapping the script's `TryOnLoad` stuff in a `try`/`catch` block similar to earlier iterations before the precompiled library was a thing also fails to resolve the problem and instead just makes the helper retry the mono loader endlessly.

This appears to have been introduced in ba9ee92a8eeacf35286464c2f318601973d9ec59; replacing the `ULibrary.bin` file with the one in 1a8c3a8a35f4d3d730fec7d035ca0821f9c9b60e does not produce this behaviour, and the script works with that version just fine.

**Comment by just-ero** [comment]
Did a mass-rename of the string `_token` at some point, embarrassingly did not think about the `type_token` field in the `MonoClass` dictionary. Fixed the name.
